<?php
/**
 * implemetns hook menu
 */
function js_menu() {
    // Menu materiales carga la lista de materiales
	$items['materiales'] = array(
	    'title' => 'Materiales',
	    'description' => 'Distintos elementos de formulario.',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('js_list_materials'),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
        // Carga la lista de presupuestos
	$items['presupuestos'] = array(
	    'title' => 'Materiales',
	    'description' => 'Distintos elementos de formulario.',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('js_lista_presupuestos'),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
        //Descarga el excel, recive como parametro el nombre del presupuesto
        $items['excel/%'] = array(
	  'title' => 'Materiales',
	  'page callback' => 'js_crear_excel',
          'page arguments' => array(1),
          'access callback' => TRUE,
	  );        
	return $items;
}
/**
 * Carga la lista de presupuestos
 * 
 */
function js_lista_presupuestos($form, &$form_state) {
    //$show_tables2 = db_query("select * from information_schema.tables where table_name like 'presupuesto%' order by CREATE_TIME desc")->fetchAll(); // Consulta lista de tablas en sql de presupuesto
    $show_tables2 = db_query("select * from aux_presupuesto_tables order by create_time desc")->fetchAll();
    $form = array();
    // Carga las cabeceras
    $form['Nombre'] = array(
      '#prefix' => '<div class="wraper-pres"><div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Nombre'),
       '#suffix' => '</div>', 
    );    
    $form['mail'] = array(
      '#prefix' => '<div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Correo'),
      '#suffix' => '</div>', 
    );      
    $form['Fecha'] = array(
      '#prefix' => '<div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Fecha'),
      '#suffix' => '</div>', 
    );          
    $form['Descarga'] = array(
      '#prefix' => '<div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Descarga'),
      '#suffix' => '</div></div>', 
    );        
    // Fin de cabeceras
    // Reccore el resultado de la consullta
    foreach ($show_tables2 as $p) {
        // Almacena los valaires de los datos
        $Nombre = $p->nombre;
        $correo = $p->correo;
        $fecha = $p->create_time;
        // Coge el Nombre real, quita los _
        $Nombreexplode = explode("_", $Nombre);
        $form[$Nombre] = array(
           '#prefix' => '<div class="wraper-pres"><div class="wraper-pres-field">',
            '#type' => 'item',
            '#title' => $Nombreexplode[1],
           '#suffix' => '</div>', 
        );
        $form[$correo] = array(
          '#prefix' => '<div class="wraper-pres-field">',
            '#type' => 'item',
            '#title' => $correo,
          '#suffix' => '</div>', 
        );         
        $form[$fecha] = array(
          '#prefix' => '<div class="wraper-pres-field">',
            '#type' => 'item',
            '#title' => $fecha,
          '#suffix' => '</div>', 
        ); 
        // Enlace a la descarga del excel
        $form['excel_' . $Nombre] = array(
          '#prefix' => '<div class="wraper-pres-field"><a href="excel/' . $Nombre . '">',
          '#type' => 'item',
          '#title' => t('Descargar'),
          '#value' => t('Descargar'),
          '#suffix' => '</a></div></div>', 
        );         
    }
    return $form;
}

/**
 * Implements list_materials
 * Carga la lista de materiales
 * Carga los nodos tipo Material
 */
function js_list_materials($form, &$form_state) {
	$form = array();
	$nodes_array_list = array();
	$nodes = node_load_multiple($nodes_array_list, array('type' => 'material'));
	$array_field_nombres = array();
        $form['nombre'] = array(
            '#type' => 'textfield',
            '#title' => t('Nombre'),
	);
        $form['mail'] = array(
            '#type' => 'textfield',
            '#title' => t('Correo'),
	);        
	foreach ($nodes as $node) {
		$vid = $node->vid;
		$nombre = $node->title;
		$id = $node->field_mat_id['und'][0]['value'];
		$precio = $node->field_mat_precio['und'][0]['value'];
		$tid = $node->field_mat_clasificacion['und'][0]['tid'];
                /*TODO: CREAR FUNCION*/
                
                
                
                
		$taxonomy = taxonomy_term_load($tid);
		$taxonomy_parents =  taxonomy_get_parents($tid);
                $array_children_parent = array();
                
                
                foreach ($taxonomy_parents as $parent) {
                    $children_parent = taxonomy_get_children($parent->tid);
                    foreach ($children_parent as $cp) {
                        array_push($array_children_parent, $cp->description);
                    }
                }
                foreach ($taxonomy_parents as $parents) {
                    $parent_name = $parents->name;
                    $childen_name = $taxonomy->name;
                    $childen_name = str_replace(" ", "_", $childen_name);
                    if ($taxonomy->description == $array_children_parent[0] && ($id - $taxonomy->description) == 1) {
                        $form[$parent_name] = array(
                            '#type' => 'fieldset',
                            '#title' => $parent_name,
                            '#collapsible' => FALSE,
                            '#collapsed' => FALSE,
			);
                    }
                    if (($id - $taxonomy->description) == 1) {
                        $form[$parent_name][$childen_name] = array(
                        	'#type' => 'fieldset',
                        	'#title' => $childen_name,
                        	'#collapsible' => FALSE,
                        	'#collapsed' => FALSE,
                        );                
                    }         
		}
                $field_nombre = 'field_nombre_' . $nombre;
                $field_cantidad = 'field_cantidad_' . $nombre;
                $field_id = 'field_id_' . $nombre;
                $field_precio = 'field_precio_' . $nombre;
                $field_tid = 'field_tid_' . $nombre;
                
		$form[$parent_name][$childen_name][$field_nombre] = array(
			'#prefix' => '<div class= "divcontainerfieldsform">',
			'#type' => 'item',
			'#title' => $nombre,
		);
		$form[$parent_name][$childen_name][$field_cantidad] = array(
    		'#attributes' => array(
        		'data-type' => 'number',
    		),			
			'#type' => 'textfield',
			'#title' => t('cantidad'),
			'#default_value' => '0',
		);

		$form[$parent_name][$childen_name][$field_id] = array(
			'#type' => 'hidden',
			'#title' => $id,
                        '#value' => $id,
		);		
		$form[$parent_name][$childen_name][$field_tid] = array(
			'#type' => 'hidden',
			'#title' => $tid,
                        '#value' => $tid,
		);                
		$form[$parent_name][$childen_name][$field_precio] = array(
			'#type' => 'hidden',
			'#title' => $precio,
			'#value' => $precio,
			'#suffix' => '</div>',
		);
		array_push($array_field_nombres, $nombre);
	}     
        $form['fecha'] = array(
            '#type' => 'hidden',
            '#title' => 'fecha',
            '#value' => REQUEST_TIME,
        );
	$form['nombre_field_array'] = array(
            '#type' => 'value',
	    '#value' => $array_field_nombres
  	);
	$form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Enviar'),
	);
        /*FIN TODO*/
	return $form;
}
/**
* Submit materials_form
*/
function js_list_materials_submit($form, &$form_state) {
	$array_field_nombres = $form_state['values']['nombre_field_array'];
	$total = 0;
	foreach ($array_field_nombres as $field_nombre) {
		$field_nombre = str_replace(" ", "_", $field_nombre);
                $field_nombre = str_replace(".", "_", $field_nombre);
		$precio = $form_state['input']['field_precio_' . $field_nombre];
		$cantidad = $form_state['input']['field_cantidad_' . $field_nombre];
		$multi = $precio * $cantidad;
		$total = $total + $multi;
	}
	js_create_insert_sql_form($form, $form_state, $array_field_nombres);
        drupal_set_message(t("Presupuesto enviado"), 'status');
}

function js_create_insert_sql_form($form, $form_state, $array_field_nombres) {
    $mail = $form_state['input']['mail'];
    $table_name = 'presupuesto_' . $form_state['input']['nombre'] . '_' . $form_state['input']['fecha'] . '';
    $sql = "insert into aux_presupuesto_tables (nombre, correo) values ('$table_name', '$mail')";
    db_query($sql);
    $sql2 = 'create table ' . $table_name . ' (id int(5) primary key, material varchar(30), cantidad int(5), precio int(5), taxonomia int(5))';
    db_query($sql2);
    $total = 0;
    foreach ($array_field_nombres as $field_nombre) {
    	$field_nombre = str_replace(" ", "_", $field_nombre);
        $field_nombre = str_replace(".", "_", $field_nombre);
        $precio = $form_state['input']['field_precio_' . $field_nombre];
	$cantidad = $form_state['input']['field_cantidad_' . $field_nombre];
        $id = $form_state['input']['field_id_' . $field_nombre];
        $tid = $form_state['input']['field_tid_' . $field_nombre];
        $sql2 = "insert into {" . $table_name . "}  (id, material, cantidad, precio, taxonomia) values ($id, '$field_nombre', $cantidad, $precio, $tid)";
        db_query($sql2); 
    }
    return;
}





function js_crear_excel($nombre_tabla_excel) {
// Set the headers to indicate this is a CSV file.
  header('Content-type: text/csv; charset=UTF-8');
  header('Content-Disposition: attachment; filename=user_signups.csv');
  header('Pragma: no-cache');
  header('Expires: 0');

  // Create a file.
  $output = fopen('php://output', 'w');

  // Column names.
    $list = array (
        array('', '', 'id', 'Nombre', 'precio', 'cantidad'),
    );
  $query = "SELECT * from " . $nombre_tabla_excel . "";
  $result = db_query($query)->fetchAll();
  // Loop through the rows.
  $puntero = 0;
  
  foreach ($result as $row) {
      $linea = array();

      
      
      
      
      
      
      $tid = $row->taxonomia;
      $taxonomy_parents =  taxonomy_get_parents($tid);
      
      
    $taxonomy = taxonomy_term_load($tid);
    $taxonomy_parents =  taxonomy_get_parents($tid);  
    $array_children_parent = array();
                
                
    foreach ($taxonomy_parents as $parent) {
        $children_parent = taxonomy_get_children($parent->tid);
        foreach ($children_parent as $cp) {
            array_push($array_children_parent, $cp->description);
        }
    }      
      foreach ($taxonomy_parents as $parents) {
        $parent_name = $parents->name;
        $childen_name = $taxonomy->name;
        $childen_name = str_replace(" ", "_", $childen_name);
        if ($taxonomy->description == $array_children_parent[0] && ($row->id - $taxonomy->description) == 1) {

            array_push($linea, $parent_name);
            array_push($list, $linea);
            $linea = array();
        }
       if (($row->id - $taxonomy->description) == 1) {

           array_push($linea, "");
            array_push($linea, $childen_name);
            array_push($list, $linea);
            $linea = array();
       }         
    }      

      
      
      array_push($linea, "");
      array_push($linea, "");
      array_push($linea, $row->id);
      array_push($linea, $row->material);
      array_push($linea, $row->precio);
      array_push($linea, $row->cantidad);
      array_push($list, $linea);
  }
  foreach($list as $fields) {
       fputcsv($output, $fields);
  }


  fclose($output);
}

