<?php
/**
 * implemetns hook menu
 */
function js_menu() {
    // Menu materiales carga la lista de materiales
	$items['materiales'] = array(
	    'title' => 'Materiales',
	    'description' => 'Distintos elementos de formulario.',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('js_list_materials'),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
        // Carga la lista de presupuestos
	$items['presupuestos'] = array(
	    'title' => 'Materiales',
	    'description' => 'Distintos elementos de formulario.',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('js_lista_presupuestos'),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );
        //Descarga el excel, recive como parametro el nombre del presupuesto
        $items['excel/%'] = array(
	  'title' => 'Materiales',
	  'page callback' => 'js_crear_excel',
          'page arguments' => array(1),
          'access callback' => TRUE,
	  );       
        $items['estado/%'] = array(
	    'title' => 'Validacion',
	    'description' => 'Validacion de formulario de materiales',
	    'page callback' => 'drupal_get_form',
	    'page arguments' => array('js_estado_pedido'),
	    'access callback' => TRUE,
	    'type' => MENU_CALLBACK,
	  );           
	return $items;
}
/**
 * ESTADO DEL PEDIDO
 */
function js_estado_pedido($form, &$form_state) {
    $current_paht = current_path();
    $nombre_tabla = substr($current_paht, 7);
    $nombre_correo = db_query("select correo from aux_presupuesto_tables where nombre = '$nombre_tabla'")->fetchAll();   
    $correo = $nombre_correo[0]->correo;
    $nombre = explode("_", $nombre_tabla);
    $show_tables = db_query("select * from " . $nombre_tabla . " where cantidad > 0")->fetchAll();  
    $is_true = db_query("select count('nombre') as contador from aux_presupuesto_tables where estado = 'TRUE' and nombre='$nombre_tabla'")->fetchAll();
    $form['nombre'] = array(
        '#type' => 'item',
        '#title' => 'Nombre: ' . $nombre[1],
    );
    $form['correo'] = array(
        '#type' => 'item',
        '#title' => 'Correo: ' . $correo,
    );    
    $form['productos'] = array(
        '#type' => 'fieldset',
        '#title' => 'Productos',
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );    
    foreach ($show_tables as $table) {
        $material = $table->material;
        $cantidad = $table->cantidad;
        if (isset($table->imagen)) {
            $imagen = $table->imagen;
            $image_options = array(
                'path' => 'sites/default/files/' . $imagen, 
                'alt' => 'Test alt',
                'title' => 'Fressnel',
                'width' => '100%',
                'attributes' => array('class' => 'field-image'),
            );
            $image = theme('image', $image_options);
            $form['productos'][$material . "_imagen_" . $imagen] = array(
                '#prefix' => '<div class="divcontainerfieldsform">',
                '#markup' => $image,
            );            
            $form['productos'][$material] = array(
                '#type' => 'item',
                '#title' => 'Nombre: ' . $material,          
            );              
        }
        else {
            $form['productos'][$material] = array(
                '#prefix' => '<div class="divcontainerfieldsform">',
                '#type' => 'item',
                '#title' => 'Nombre: ' . $material,          
            );            
        }

        $form['productos'][$material . '_cantidad'] = array(
            '#type' => 'item',
            '#title' => 'Cantidad: ' . $cantidad,  
            '#suffix' => '</div>', 
        );
    }
    if ($is_true[0]->contador != 1) {
        $form['submit'] = array(
            '#type' => 'submit',
            '#value' => t('Validar'),
        );        
    }   
    else {
        drupal_set_message('Su documento ya ha sido enviado, espere respuesta');
    }
    $form['Excel'] = array(
        '#attributes' => array(
            'class' => array(
              'descargaexcelestado'
            ),
         ), 
        '#prefix' => '<a class="descargaexcelestado" href="excel/' . $nombre_tabla . '">',
        '#type' => 'item',
        '#title' => t('Descargar Excel'),
        '#suffix' => '</a>', 
    );   
    $form['tabla'] = array(
       '#type' => 'value',
       '#value' => $nombre_tabla,
    );
    
    return $form;
}
function js_estado_pedido_submit($form, $form_state) {
    $nombre_tabla = $form['tabla']['#value'];
    $sql = db_query("UPDATE aux_presupuesto_tables SET estado = 'TRUE' where nombre = '$nombre_tabla';");
        $params = array('body' => 'hola');
        $key = 'test_email';
        $to = 'carlos_ruizc@msn.com';
        $from = 'carlos_ruizc@msn.com';
        $mail = drupal_mail('js', $key, $to, language_default(), $params, $from);
    drupal_set_message('Presupuesto enviado');
}




function js_mail($key, &$message, $params) {
  $language = $message['language'];
  switch ($key) {
    //switching on $key lets you create variations of the email based on the $key parameter
    case 'test_email':
      $message['subject'] = t('Test Email');
      //the email body is here, inside the $message array
      $message['body'][] = $params['body'];
      break;
  }
}
/**
 * Carga la lista de presupuestos
 * 
 */
function js_lista_presupuestos($form, &$form_state) {
    //$show_tables2 = db_query("select * from information_schema.tables where table_name like 'presupuesto%' order by CREATE_TIME desc")->fetchAll(); // Consulta lista de tablas en sql de presupuesto
    $show_tables2 = db_query("select * from aux_presupuesto_tables order by create_time desc")->fetchAll();
    $form = array();
    // Carga las cabeceras
    $form['Nombre'] = array(
      '#prefix' => '<div class="wraper-pres"><div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Nombre'),
       '#suffix' => '</div>', 
    );    
    $form['mail'] = array(
      '#prefix' => '<div class="wraper-pres-field">',
       '#type' => 'item',
       '#title' => t('Correo'),
      '#suffix' => '</div>', 
    );      
    $form['Fecha'] = array(
      '#prefix' => '<div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Fecha'),
      '#suffix' => '</div>', 
    );          
    $form['Descarga'] = array(
      '#prefix' => '<div class="wraper-pres-field">',
       '#type' => 'item',
        '#title' => t('Descarga'),
      '#suffix' => '</div></div>', 
    );        
    // Fin de cabeceras
    // Reccore el resultado de la consullta
    foreach ($show_tables2 as $p) {
        // Almacena los valaires de los datos
        $Nombre = $p->nombre;
        $correo = $p->correo;
        $fecha = $p->create_time;
        // Coge el Nombre real, quita los _
        $Nombreexplode = explode("_", $Nombre);
        $form[$Nombre] = array(
           '#prefix' => '<div class="wraper-pres"><div class="wraper-pres-field">',
            '#type' => 'item',
            '#title' => $Nombreexplode[1],
           '#suffix' => '</div>', 
        );
        $form[$correo] = array(
          '#prefix' => '<div class="wraper-pres-field">',
            '#type' => 'item',
            '#title' => $correo,
          '#suffix' => '</div>', 
        );         
        $form[$fecha] = array(
          '#prefix' => '<div class="wraper-pres-field">',
            '#type' => 'item',
            '#title' => $fecha,
          '#suffix' => '</div>', 
        ); 
        // Enlace a la descarga del excel
        $form['excel_' . $Nombre] = array(
          '#prefix' => '<div class="wraper-pres-field"><a href="excel/' . $Nombre . '">',
          '#type' => 'item',
          '#title' => t('Descargar'),
          '#value' => t('Descargar'),
          '#suffix' => '</a></div></div>', 
        );         
    }
    return $form;
}

/**
 * Implements list_materials
 * Carga la lista de materiales
 * Carga los nodos tipo Material
 */
function js_list_materials($form, &$form_state) {
//	$form = array();
//	$nodes_array_list = array();
//	$nodes = node_load_multiple($nodes_array_list, array('type' => 'material'));
//        $array_images = array();
//	$array_field_nombres = array();  
//        $form['nombre'] = array(
//            '#type' => 'textfield',
//            '#title' => t('Nombre'),
//        );
//        $form['mail'] = array(
//            '#type' => 'textfield',
//            '#title' => t('Correo'),
//        );    
//	foreach ($nodes as $node) {
//		$vid = $node->vid;
//		$nombre = $node->title;
//		$id = $node->field_mat_id['und'][0]['value'];
//		$precio = $node->field_mat_precio['und'][0]['value'];
//		$tid = $node->field_mat_clasificacion['und'][0]['tid'];
//                /*TODO: CREAR FUNCION*/
//                
//                
//                
//		$taxonomy = taxonomy_term_load($tid);
//		$taxonomy_parents =  taxonomy_get_parents($tid);
//                $array_children_parent = array();
//                
//                
//                foreach ($taxonomy_parents as $parent) {
//                    $children_parent = taxonomy_get_children($parent->tid);
//                    foreach ($children_parent as $cp) {
//                        array_push($array_children_parent, $cp->description);
//                    }
//                }
//                foreach ($taxonomy_parents as $parents) {
//                    $parent_name = $parents->name;
//                    $childen_name = $taxonomy->name;
//                    $childen_name = str_replace(" ", "_", $childen_name);
//                    if ($taxonomy->description == $array_children_parent[0] && ($id - $taxonomy->description) == 1) {
//                        $form[$parent_name] = array(
//                            '#type' => 'fieldset',
//                            '#title' => $parent_name,
//                            '#collapsible' => TRUE,
//                            '#collapsed' => TRUE,
//			);
//                    }
//                    if (($id - $taxonomy->description) == 1) {
//                        $form[$parent_name][$childen_name] = array(
//                        	'#type' => 'fieldset',
//                        	'#title' => $childen_name,
//                        	'#collapsible' => TRUE,
//                        	'#collapsed' => TRUE,
//                        );                
//                    }         
//		}
//                $field_nombre = 'field_nombre_' . $nombre;
//                $field_cantidad = 'field_cantidad_' . $nombre;
//                $field_id = 'field_id_' . $nombre;
//                $field_precio = 'field_precio_' . $nombre;
//                $field_tid = 'field_tid_' . $nombre;
//                $field_imagen = 'field_imagen_' . $nombre;
//                if(isset($node->field_mat_imagen['und'][0]['filename'])) {
//                    $imagen = $node->field_mat_imagen['und'][0]['filename'];
//                    $image_options = array(
//                        'path' => 'sites/default/files/' . $node->field_mat_imagen['und'][0]['filename'], 
//                        'alt' => 'Test alt',
//                        'title' => 'Fressnel',
//                        'width' => '100%',
//                        'attributes' => array('class' => 'field-image'),
//                    );
//                    $image = theme('image', $image_options);
//                    $form[$parent_name][$childen_name][$field_imagen] = array(
//                        '#prefix' => '<div class= "divcontainerfieldsform">',
//                        '#markup' => $image,
//                    );
//                    $form[$parent_name][$childen_name][$field_nombre] = array(
//                        '#type' => 'item',
//                        '#title' => $nombre,
//                    );
//                    $nombre = str_replace(" ", "_", $nombre);
//                    $array_images[$nombre] = $imagen;
//                    $nombre = str_replace("_", " ", $nombre);
//                }
//                else {
//                    $form[$parent_name][$childen_name][$field_nombre] = array(
//                        '#prefix' => '<div class= "divcontainerfieldsform">',
//                        '#type' => 'item',
//                        '#title' => $nombre,
//                    );
//                }
//                
//
//		$form[$parent_name][$childen_name][$field_cantidad] = array(
//    		'#attributes' => array(
//        		'data-type' => 'number',
//    		),			
//			'#type' => 'textfield',
//			'#title' => t('cantidad'),
//			'#default_value' => '0',
//		);
//
//		$form[$parent_name][$childen_name][$field_id] = array(
//			'#type' => 'hidden',
//			'#title' => $id,
//                        '#value' => $id,
//		);		
//		$form[$parent_name][$childen_name][$field_tid] = array(
//			'#type' => 'hidden',
//			'#title' => $tid,
//                        '#value' => $tid,
//		);                
//		$form[$parent_name][$childen_name][$field_precio] = array(
//			'#type' => 'hidden',
//			'#title' => $precio,
//			'#value' => $precio,
//			'#suffix' => '</div>',
//		);
//		array_push($array_field_nombres, $nombre);
//	}     
//        $form['fecha'] = array(
//            '#type' => 'hidden',
//            '#title' => 'fecha',
//            '#value' => REQUEST_TIME,
//        );
//	$form['nombre_field_array'] = array(
//            '#type' => 'value',
//	    '#value' => $array_field_nombres,
//  	);
//	$form['imagenes_array'] = array(
//            '#type' => 'value',
//	    '#value' => $array_images,
//  	);        
//	$form['submit'] = array(
//            '#type' => 'submit',
//            '#value' => t('Enviar'),
//	);
//        /*FIN TODO*/
//	return $form;
}
/**
* Submit materials_form
*/
function js_list_materials_submit($form, &$form_state) {
    dpm("hola1");
//        $estado = 'FALSE';
//	$array_field_nombres = $form_state['values']['nombre_field_array'];
//	$total = 0;
//	foreach ($array_field_nombres as $field_nombre) {
//		$field_nombre = str_replace(" ", "_", $field_nombre);
//                $field_nombre = str_replace(".", "_", $field_nombre);
//		$precio = $form_state['input']['field_precio_' . $field_nombre];
//		$cantidad = $form_state['input']['field_cantidad_' . $field_nombre];
//		$multi = $precio * $cantidad;
//		$total = $total + $multi;
//	}
//	js_create_insert_sql_form($form, $form_state, $array_field_nombres, $estado);
}

function js_create_insert_sql_form($form, $form_state, $array_field_nombres, $estado) {
    dpm('hola');
//    $mail = $form_state['input']['mail'];
//    $table_name = 'presupuesto_' . $form_state['input']['nombre'] . '_' . $form_state['input']['fecha'] . '';
//    $sql = "insert into aux_presupuesto_tables (nombre, correo, estado) values ('$table_name', '$mail', '$estado')";
//    db_query($sql);
//    $sql2 = 'create table ' . $table_name . ' (id int(5), material varchar(100), imagen varchar(30), cantidad int(5), precio int(5), taxonomia int(5))';
//    db_query($sql2);
//    $total = 0;
//    foreach ($array_field_nombres as $field_nombre) {
//    	$field_nombre = str_replace(" ", "_", $field_nombre);
//        $field_nombre = str_replace(".", "_", $field_nombre);
//        $precio = $form_state['input']['field_precio_' . $field_nombre];
//	$cantidad = $form_state['input']['field_cantidad_' . $field_nombre];
//        $id = $form_state['input']['field_id_' . $field_nombre];
//        $tid = $form_state['input']['field_tid_' . $field_nombre];
//        if(isset($form_state['values']['imagenes_array'][$field_nombre])) {
//            $imagen = $form_state['values']['imagenes_array'][$field_nombre];
//            if($cantidad > 0) {
//                //$sql2 = "insert into {" . $table_name . "}  (id, material, imagen, cantidad, precio, taxonomia) values ($id, '$field_nombre', '$imagen', $cantidad, $precio, $tid)";
//            }
//        }
//        else {
//            if($cantidad > 0) {
//                //$sql2 = "insert into {" . $table_name . "}  (id, material, cantidad, precio, taxonomia) values ($id, '$field_nombre', $cantidad, $precio, $tid)";
//            }
//        }
//        //db_query($sql2); 
//    }
//    dpm("asddasdasdasda");
//    drupal_goto('estado/' . $table_name);
//    return;
}





function js_crear_excel($nombre_tabla_excel) {
// Set the headers to indicate this is a CSV file.
  header('Content-type: text/csv; charset=UTF-8');
  header('Content-Disposition: attachment; filename=' . $nombre_tabla_excel . '.csv');
  header('Pragma: no-cache');
  header('Expires: 0');

  // Create a file.
  $output = fopen('php://output', 'w');

  // Column names.
    $list = array (
        array('', '', 'id', 'Nombre', 'precio', 'cantidad'),
    );
  $query = "SELECT * from " . $nombre_tabla_excel . "";
  $result = db_query($query)->fetchAll();
  // Loop through the rows.
  $puntero = 0;
  
  foreach ($result as $row) {
      $linea = array();

      
      
      
      
      
      
      $tid = $row->taxonomia;
      $taxonomy_parents =  taxonomy_get_parents($tid);
      
      
    $taxonomy = taxonomy_term_load($tid);
    $taxonomy_parents =  taxonomy_get_parents($tid);  
    $array_children_parent = array();
                
                
    foreach ($taxonomy_parents as $parent) {
        $children_parent = taxonomy_get_children($parent->tid);
        foreach ($children_parent as $cp) {
            array_push($array_children_parent, $cp->description);
        }
    }      
      foreach ($taxonomy_parents as $parents) {
        $parent_name = $parents->name;
        $childen_name = $taxonomy->name;
        $childen_name = str_replace(" ", "_", $childen_name);
        if ($taxonomy->description == $array_children_parent[0] && ($row->id - $taxonomy->description) == 1) {

            array_push($linea, $parent_name);
            array_push($list, $linea);
            $linea = array();
        }
       if (($row->id - $taxonomy->description) == 1) {

           array_push($linea, "");
            array_push($linea, $childen_name);
            array_push($list, $linea);
            $linea = array();
       }         
    }      

      
      
      array_push($linea, "");
      array_push($linea, "");
      array_push($linea, $row->id);
      array_push($linea, $row->material);
      array_push($linea, $row->precio);
      array_push($linea, $row->cantidad);
      array_push($list, $linea);
  }
  foreach($list as $fields) {
       fputcsv($output, $fields);
  }


  fclose($output);
}

